# Generated by Django 6.0.4 on 2026-04-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
